version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: leitura-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: leitura_livre
      POSTGRES_USER: leitura
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "leitura"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leitura-api
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=leitura_livre;Username=leitura;Password=admin
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
